[deploy]
startCommand = "chmod +x start.sh && ./start.sh"
healthcheckPath = "/gateway/v1/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"

[build]
buildCommand = "echo 'Building Gateway Service...'"

[env]
DISABLE_ML_MODEL = "true" 