[deploy]
startCommand = "chmod +x start.sh && ./start.sh"
healthcheckPath = "/gateway/v1/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"

[build]
buildCommand = "echo 'Building Gateway Service...'"

[env]
# ML 설정 (Gateway는 ML 사용 안함)
DISABLE_ML_MODEL = "true"

# 서비스 연동 설정 (Railway Private Networking)
NEWS_SERVICE_URL = "http://news-service.railway.internal:8002"
SASB_SERVICE_URL = "http://sasb-service.railway.internal:8003"
MATERIAL_SERVICE_URL = "http://material-service.railway.internal:8004"

# 서비스 설정
PYTHONPATH = "/app"
APP_NAME = "News Gateway API"
VERSION = "3.0.0"
DEBUG = "false"
ENVIRONMENT = "production" 