version: '3.8'

services:
  news-service:
    build: .
    container_name: news-service
    ports:
      - "8002:8002"
    environment:
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - SERVICE_PORT=8002
      - SERVICE_HOST=0.0.0.0
      - LOG_LEVEL=INFO
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - news-network

networks:
  news-network:
    driver: bridge 