[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"

[build]
buildCommand = "echo 'Building Material Service...'"

[env]
# ML 설정 (Material Service는 ML 사용 안함)
DISABLE_ML_MODEL = "true"

# Redis 설정 (SASB Service와 데이터 공유)
REDIS_URL = "${{REDIS_PRIVATE_URL}}"
REDIS_DB = "0"

# SASB Service 직접 연동 (실제 배포된 SASB Service URL 사용)
# 배포 후 SASB Service URL로 업데이트 필요
SASB_SERVICE_URL = "https://sasb-service.up.railway.app"

# 서비스 설정
PYTHONPATH = "/app"
APP_NAME = "Material Assessment Service" 
VERSION = "2.0.0"
DEBUG = "false"
ENVIRONMENT = "production" 