[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"

[build]
buildCommand = "echo 'Building SASB Service...'"

[env]
# ML 설정 (Railway 환경에서는 ML 모델 비활성화)
MODEL_BASE_PATH = "/home/appuser/app/shared/models"
MODEL_NAME = "test222"
DISABLE_ML_MODEL = "true"

# Redis 설정 (Railway 자동 환경변수 사용)
# Railway는 Redis Database 추가 시 자동으로 REDIS_URL 주입
REDIS_URL = "${{REDIS_URL}}"
REDIS_DB = "0"

# Celery 설정 (Railway Redis 자동 환경변수 사용)
CELERY_BROKER_URL = "${{REDIS_URL}}"
CELERY_RESULT_BACKEND = "${{REDIS_URL}}"

# 서비스 설정
PYTHONPATH = "/home/appuser/app"
APP_NAME = "SASB Analysis Service"
VERSION = "2.0.0"
DEBUG = "false"
ENVIRONMENT = "production" 